name: KC

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run on (created if missing)"
        type: string
        default: "main"
        required: true
      prompt_file:
        description: "Prompt file in repo (e.g., prompts/test_prompt.md)"
        type: string
        default: "prompts/test_prompt.md"
        required: true
      provider:
        description: "LLM provider"
        type: choice
        options:
          - kilocode_hosted        # uses provider: kilocode (token+model)
          - self_hosted_openai     # uses provider: openai-compatible
          - xai_direct             # uses provider: openai-compatible
          - openrouter             # uses provider: openai-compatible
        default: kilocode_hosted
        required: true
      model:
        description: "Model id for the provider (e.g., xai/grok-code-fast-1, anthropic/claude-sonnet-4.5)"
        type: string
        default: "xai/grok-code-fast-1"
        required: true
      mode:
        description: "Kilocode mode (architect|code|debug|ask|orchestrator)"
        type: string
        default: "orchestrator"
        required: true
      timeout_sec:
        description: "Max seconds for Kilo run"
        type: string
        default: "1200"
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  kilo:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      TARGET_REPO: familiarizeptyltd/docs.familiarize.com
      WORKDIR: docs_repo
      BRANCH: ${{ inputs.branch }}
      PROMPT_FILE: ${{ inputs.prompt_file }}
      KILO_TIMEOUT: ${{ inputs.timeout_sec }}
      PROVIDER: ${{ inputs.provider }}
      MODEL: ${{ inputs.model }}
      MODE: ${{ inputs.mode }}

    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      - name: Checkout target repo (private)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPO }}
          path: ${{ env.WORKDIR }}
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
          submodules: true

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Kilocode CLI
        run: npm i -g @kilocode/cli

      # Configure CLI provider NON-INTERACTIVELY for the chosen option
      - name: Write Kilocode CLI config (provider + auto-approvals)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p ~/.kilocode/cli

          # Build provider block depending on selection
          if [ "${PROVIDER}" = "kilocode_hosted" ]; then
            # --- OFFICIAL KILOCODE PROVIDER (token + model) ---
            test -n "${{ secrets.KILOCODE_API_KEY }}" || { echo "::error::Missing secrets.KILOCODE_API_KEY"; exit 1; }
            PROVIDER_JSON=$(cat <<JSON
            {
              "version": 1,
              "currentProvider": "kilocode",
              "providers": {
                "kilocode": {
                  "type": "kilocode",
                  "kilocodeToken": "${{ secrets.KILOCODE_API_KEY }}",
                  "kilocodeModel": "${MODEL}"
                }
              },
              "autoApproval": {
                "enabled": true,
                "read":  { "enabled": true, "outside": false },
                "write": { "enabled": true, "outside": false, "protected": false },
                "execute": {
                  "enabled": true,
                  "allowed": ["git", "node", "npm", "pnpm"],
                  "denied": ["sudo", "rm -rf", "dd", "mkfs", "shutdown", "reboot", "git push --force"]
                },
                "browser": { "enabled": false },
                "mcp": { "enabled": true },
                "mode": { "enabled": true },
                "subtasks": { "enabled": true },
                "question": { "enabled": false, "timeout": 60 },
                "retry": { "enabled": true, "delay": 10 },
                "todo": { "enabled": true }
              }
            }
            JSON
            )
          else
            # --- OPENAI-COMPATIBLE PROVIDERS (baseUrl + key + model) ---
            case "${PROVIDER}" in
              self_hosted_openai)
                OPENAI_BASE_URL="${{ secrets.LLM_BASE_URL }}"
                OPENAI_API_KEY="${{ secrets.LLM_API_KEY }}"
                ;;
              xai_direct)
                OPENAI_BASE_URL="https://api.x.ai"
                OPENAI_API_KEY="${{ secrets.XAI_API_KEY }}"
                ;;
              openrouter)
                OPENAI_BASE_URL="https://openrouter.ai/api/v1"
                OPENAI_API_KEY="${{ secrets.OPENROUTER_API_KEY }}"
                ;;
              *) echo "::error::Unknown provider: ${PROVIDER}"; exit 1;;
            esac

            test -n "${OPENAI_API_KEY}" || { echo "::error::Missing API key secret for ${PROVIDER}"; exit 1; }
            test -n "${OPENAI_BASE_URL}" || { echo "::error::Missing base URL for ${PROVIDER}"; exit 1; }

            PROVIDER_JSON=$(cat <<JSON
            {
              "version": 1,
              "currentProvider": "openai-compatible",
              "providers": {
                "openai-compatible": {
                  "type": "openai-compatible",
                  "baseUrl": "${OPENAI_BASE_URL}",
                  "apiKeyEnv": "OPENAI_API_KEY",
                  "model": "${MODEL}"
                }
              },
              "autoApproval": {
                "enabled": true,
                "read":  { "enabled": true, "outside": false },
                "write": { "enabled": true, "outside": false, "protected": false },
                "execute": {
                  "enabled": true,
                  "allowed": ["git", "node", "npm", "pnpm"],
                  "denied": ["sudo", "rm -rf", "dd", "mkfs", "shutdown", "reboot", "git push --force"]
                },
                "browser": { "enabled": false },
                "mcp": { "enabled": true },
                "mode": { "enabled": true },
                "subtasks": { "enabled": true },
                "question": { "enabled": false, "timeout": 60 },
                "retry": { "enabled": true, "delay": 10 },
                "todo": { "enabled": true }
              }
            }
            JSON
            )

            # Export OPENAI_* env for the run step
            echo "OPENAI_BASE_URL=${OPENAI_BASE_URL}" >> $GITHUB_ENV
            echo "OPENAI_API_KEY=${OPENAI_API_KEY}"   >> $GITHUB_ENV
          fi

          printf '%s\n' "${PROVIDER_JSON}" > ~/.kilocode/cli/config.json

      - name: Mark repo as safe for Git
        working-directory: ${{ env.WORKDIR }}
        run: git config --global --add safe.directory "${PWD}"

      - name: Prepare branch
        working-directory: ${{ env.WORKDIR }}
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin --prune
          if git ls-remote --exit-code --heads origin "${BRANCH}" >/dev/null 2>&1; then
            git checkout "${BRANCH}"
            git pull --ff-only origin "${BRANCH}"
          else
            git checkout -B "${BRANCH}" origin/main || git checkout -B "${BRANCH}"
          fi

      - name: Verify prompt file exists
        working-directory: ${{ env.WORKDIR }}
        run: |
          test -f "${PROMPT_FILE}" || { echo "::error::Prompt not found: ${PROMPT_FILE}"; exit 1; }

      - name: Set non-interactive env flags
        run: |
          echo "CI=true" >> $GITHUB_ENV
          echo "KILOCODE_CI=true" >> $GITHUB_ENV
          echo "NO_COLOR=1" >> $GITHUB_ENV
          echo "TERM=xterm" >> $GITHUB_ENV

      - name: Run Kilocode autonomously with prompt
        working-directory: ${{ env.WORKDIR }}
        shell: bash
        run: |
          set -euo pipefail
          echo "Provider=${PROVIDER}  Model=${MODEL}  Mode=${MODE}  Timeout=${KILO_TIMEOUT}"
          # Small hint to the agent: use the selected mode (auto-approval already allows switching)
          {
            echo "[mode] Use ${MODE}.";
            cat "${PROMPT_FILE}";
          } | kilocode --auto --timeout "${KILO_TIMEOUT}" --workspace "${PWD}" --mode "${MODE}" || rc=$?

          if [ "${rc:-0}" = "124" ]; then
            echo "::error::Kilocode timed out after ${KILO_TIMEOUT}s"; exit 124
          elif [ -n "${rc:-}" ] && [ "${rc}" != "0" ]; then
            echo "::error::Kilocode exited with error code ${rc}"; exit "${rc}"
          fi

      - name: Commit & push changes (if any)
        working-directory: ${{ env.WORKDIR }}
        run: |
          set -euo pipefail
          if ! git diff --no-ext-diff --quiet; then
            git add -A
            git commit -m "Kilocode (auto): ${PROMPT_FILE} via ${PROVIDER}:${MODEL} [mode=${MODE}]"
            git push origin HEAD:"${BRANCH}"
            echo "Pushed updates to ${BRANCH}."
          else
            echo "No changes produced by Kilocode."
          fi
