name: Kilo Code Autonomous Fix

on:
  pull_request:
    branches:
      - main

jobs:
  kilocode-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Kilo Code CLI
        run: npm install -g @kilocode/cli

      - name: Fix code with Kilo Code
        env:
          KILOCODE_API_KEY: ${{ secrets.KILOCODE_API_KEY }}
        run: |
          # The agent works directly on the code, so you'll need to handle Git operations after it finishes.
          git config user.email "kilocode@users.noreply.github.com"
          git config user.name "Kilo Code"
          echo "Write a short article on Price to Earnings Ratio and store in root of the repository." | kilocode --auto
          
          # Stage, commit, and push the changes made by Kilo Code
          git add .
          git commit -m "Kilo Code: Added a test article." || echo "No changes to commit"
          git push
