name: KiloCode - headless demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      KILOCODE_TOKEN: ${{ secrets.KILOCODE_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Basics
        run: |
          set -euxo pipefail
          node -v
          npm -v

      - name: Install KiloCode CLI
        run: |
          set -euxo pipefail
          npm install -g @kilocode/cli
          kilocode --version || true

      - name: Configure KiloCode (non-interactive)
        run: |
          set -euxo pipefail
          mkdir -p ~/.kilocode/cli ~/.kilocode
          cat > ~/.kilocode/cli/config.json <<'JSON'
          {
            "version": 1,
            "currentProvider": "default",
            "providers": [
              {
                "id": "default",
                "provider": "kilocode",
                "kilocodeToken": "__KILOCODE_TOKEN__",
                "kilocodeModel": "openai/gpt-4o-mini"
              }
            ],
            "autoApproval": {
              "enabled": true,
              "read":    { "enabled": true,  "outside": false },
              "write":   { "enabled": false, "outside": false, "protected": false },
              "execute": { "enabled": false, "allowed": [], "denied": [] },
              "question": { "enabled": false, "timeout": 30 },
              "retry":    { "enabled": true,  "delay": 5 }
            }
          }
          JSON
          cp ~/.kilocode/cli/config.json ~/.kilocode/config.json
          sed -i "s/__KILOCODE_TOKEN__/${KILOCODE_TOKEN//\//\\/}/" ~/.kilocode/cli/config.json ~/.kilocode/config.json
          sudo apt-get update -y >/dev/null && sudo apt-get install -y jq >/dev/null
          jq '(.providers[0].kilocodeToken)="***REDACTED***"' ~/.kilocode/cli/config.json

      - name: Verify profile & balance (Bearer)
        run: |
          set -euxo pipefail
          sudo apt-get update -y && sudo apt-get install -y jq
          curl -fsS -H "Authorization: Bearer ${KILOCODE_TOKEN}" https://api.kilocode.ai/api/profile | jq .
          curl -fsS -H "Authorization: Bearer ${KILOCODE_TOKEN}" https://api.kilocode.ai/api/profile/balance | jq .

      - name: Ask KiloCode to PRINT file content (headless via PTY)
        env:
          TERM: xterm-256color
          CI: "true"
          NO_COLOR: "1"
          # If the CLI honors these, they help; harmless otherwise:
          KILOCODE_HEADLESS: "1"
          KILOCODE_NONINTERACTIVE: "1"
          DEBUG: "kilocode:*,axios:*"
        run: |
          set -euxo pipefail
          UTC_NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

          # Build the prompt as a single line (CLI expects an argument in CI)
          cat > prompt.txt <<'PROMPT'
          You are running HEADLESS in CI, so do NOT use any file-writing or execution tools.
          Instead, PRINT ONLY the exact contents for the file KILOCODE_DEMO.md between the markers:
          <<<BEGIN>>>
          ...file content...
          <<<END>>>

          Requirements for the content:
          - Markdown H1: "KiloCode CLI Demo"
          - Include the placeholder token {{UTC_NOW}} on its own line for timestamp
          - Add a short note line: "Hello from GitHub Actions."
          - Keep output strictly idempotent and deterministic
          - No extra commentary before/after the markers
          PROMPT

          PROMPT_ARG="$(tr '\n' ' ' < prompt.txt)"

          # Allocate a PTY and pass the prompt as an argument
          set +e
          script -qfec "kilocode --auto \"${PROMPT_ARG}\" --timeout 300" /dev/null 2>&1 | tee kilocode.log
          EXIT=$?
          set -e
          echo "kilocode exit code: $EXIT"

          # Extract the content between markers
          awk '/^<<<BEGIN>>>/{flag=1;next}/^<<<END>>>/{flag=0}flag' kilocode.log > KILOCODE_DEMO.template || true

          if [ ! -s KILOCODE_DEMO.template ]; then
            echo "::error::KiloCode did not return delimited content. See kilocode.log tail:"
            tail -n 200 kilocode.log || true
            exit 1
          fi

          # Substitute timestamp and write the final file
          sed "s/{{UTC_NOW}}/${UTC_NOW}/g" KILOCODE_DEMO.template > KILOCODE_DEMO.md

          echo "Preview:"
          head -n 50 KILOCODE_DEMO.md

      - name: Commit & push if changed
        run: |
          set -euxo pipefail
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add KILOCODE_DEMO.md
            git commit -m "chore: add/update KILOCODE_DEMO.md via KiloCode (headless demo)"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Attach KiloCode logs (artifact)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: kilocode-log
          path: kilocode.log
