name: KiloCode - headless demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      KILOCODE_TOKEN: ${{ secrets.KILOCODE_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Basics
        run: |
          set -euxo pipefail
          node -v
          npm -v

      - name: Install KiloCode CLI
        run: |
          set -euxo pipefail
          npm install -g @kilocode/cli
          kilocode --version || true

      - name: Configure KiloCode (non-interactive; enable writes)
        run: |
          set -euxo pipefail
          mkdir -p ~/.kilocode/cli ~/.kilocode
          cat > ~/.kilocode/cli/config.json <<'JSON'
          {
            "version": 1,
            "currentProvider": "default",
            "providers": [
              {
                "id": "default",
                "provider": "kilocode",
                "kilocodeToken": "__KILOCODE_TOKEN__",
                "kilocodeModel": "openai/gpt-4o-mini"
              }
            ],
            "autoApproval": {
              "enabled": true,
              "read":    { "enabled": true,  "outside": false },
              "write":   { "enabled": true,  "outside": false, "protected": false },
              "execute": { "enabled": false, "allowed": [], "denied": [] },
              "question": { "enabled": false, "timeout": 30 },
              "retry":    { "enabled": true,  "delay": 5 }
            }
          }
          JSON
          cp ~/.kilocode/cli/config.json ~/.kilocode/config.json
          sed -i "s/__KILOCODE_TOKEN__/${KILOCODE_TOKEN//\//\\/}/" ~/.kilocode/cli/config.json ~/.kilocode/config.json
          sudo apt-get update -y >/dev/null && sudo apt-get install -y jq >/dev/null
          jq '(.providers[0].kilocodeToken)="***REDACTED***"' ~/.kilocode/cli/config.json

      - name: Verify profile & balance (Bearer)
        run: |
          set -euxo pipefail
          sudo apt-get update -y && sudo apt-get install -y jq
          curl -fsS -H "Authorization: Bearer ${KILOCODE_TOKEN}" https://api.kilocode.ai/api/profile | jq .
          curl -fsS -H "Authorization: Bearer ${KILOCODE_TOKEN}" https://api.kilocode.ai/api/profile/balance | jq .

      - name: Try KiloCode to WRITE the file (experiments)
        env:
          CI: "true"
          TERM: "xterm-256color"
          NO_COLOR: "1"
          DEBUG: "kilocode:*,axios:*"
          KILOCODE_HEADLESS: "0"
          KILOCODE_NONINTERACTIVE: "1"
          KILOCODE_ALLOW_WRITES: "1"
          KILOCODE_ALLOW_TOOLS: "1"
        run: |
          set -euxo pipefail

          cat > prompt.txt <<'PROMPT'
          Create or update a file named KILOCODE_DEMO.md at the repo root.
          The content must be exactly:
          # KiloCode CLI Demo
          {{UTC_NOW}}
          Hello from GitHub Actions.
          PROMPT

          PROMPT_ARG="$(tr '\n' ' ' < prompt.txt)"

          try_kc () {
            set +e
            bash -lc "$1" 2>&1 | tee -a kilocode.log
            rc=${PIPESTATUS[0]}
            set -e
            echo "cmd exit=$rc"
            [ -f KILOCODE_DEMO.md ] && return 0 || return 1
          }

          # A: plain arg
          try_kc "kilocode --auto \"${PROMPT_ARG}\" --timeout 300" \
            || \
          # B: with a pseudo-tty
          try_kc "script -qfec 'kilocode --auto \"${PROMPT_ARG}\" --timeout 300' /dev/null" \
            || \
          # C: stdin
          try_kc "printf '%s' \"${PROMPT_ARG}\" | kilocode --auto --timeout 300" \
            || true

          if [ -f KILOCODE_DEMO.md ]; then
            echo "::notice::KiloCode created the file."
          else
            echo "::warning::KiloCode still didn't write in CI; fallback step will synthesize it."
          fi

      - name: Fallback (synthesize file if CLI did not write it)
        run: |
          set -euxo pipefail
          if [ ! -f KILOCODE_DEMO.md ]; then
            UTC_NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
            {
              echo "# KiloCode CLI Demo"
              echo "${UTC_NOW}"
              echo "Hello from GitHub Actions."
            } > KILOCODE_DEMO.md
            echo "::notice::Wrote KILOCODE_DEMO.md via fallback."
          fi
          echo "Preview:"
          head -n 20 KILOCODE_DEMO.md

      - name: Commit & push if changed
        run: |
          set -euxo pipefail
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add KILOCODE_DEMO.md
            git commit -m "chore: add/update KILOCODE_DEMO.md (CLI headless demo)"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Attach KiloCode logs (artifact)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: kilocode-log
          path: kilocode.log
